### ISSUE TITLE
Plugin not working with Phlox theme.

### ISSUE THREAD

**Issue by rvarun11** [brainstormforce/header-footer-elementor#128]
Hello,
I am trying to make custom headers and footers for my site but I am unable to do. The problem is when I create a New Template and select Edit with Elementor, a new canvas opens like it usually does with Elementor as shown below, but I am not able to click on anything. 

![plugin](https://user-images.githubusercontent.com/29220148/48364490-8becbf00-e6ce-11e8-923c-5583ce221b6c.png)

I try to click on the "+" icon to create a new section or drag and drop an element from the sidebar but I am unable to do. I created my whole website using Elementor and had no issues.
My website is: test.innovationmotive.com 
Plugin Version: 1.0.16
Theme Version: 2.2.26

**Comment by ivanthemeh** [comment]
Did you ever fix this or just rollback phlox or ehf?

**Comment by rvarun11** [comment]
No, the problem is still there. I tried roll backing Phlox to previous versions but that did not work. I ended up using Anywhere Elementor instead for my footers.

**Comment by SuryawanshiPrajakta** [comment]
Hello @ivanthemeh and @rvarun11,

Thank you for getting in touch with us!

Could you please provide us with few steps to reproduce this issue if you are still facing it?

As we tried to reproduce this at our end, we were able to create a header and footer with the Phlox theme.

Let us know if we are missing anything. Looking forward to hearing from you.
