### ISSUE TITLE
I want to fetch the list of all headers and footers templates created within this plugin.

### ISSUE THREAD

**Issue by themechampion** [brainstormforce/header-footer-elementor#345]
Could you please navigate me to the code where I can fetch the list of headers and footer. basically, I am trying to implement this plugin in my theme and having an stage where I need  to know whether this plugin have data or not?

**Comment by Nikschavan** [comment]
All the templates generated by this plugin are stored in a separate post type [`elementor-hf`](https://github.com/brainstormforce/header-footer-elementor/blob/dddc26856dcd5b15a396f6fa6fde34a96ff9aaff/admin/class-hfe-admin.php#L219-L249)

You should be able to use `WP_Query` with `post_type -> elementor-hf` to query the posts created by this plugin.

**Comment by Nikschavan** [comment]
I am closing this issue, but feel free to reply to this issue if there is any more questions that you have.
