### ISSUE TITLE
Loading of Elementor alignments delayed

### ISSUE THREAD

**Issue by adamjh22** [brainstormforce/header-footer-elementor#347]
### Describe the bug:
When using the navigation menu plugin on Elementor. On mobile devices, upon the first open of the menu when clicking the burger icon, the menu is aligned to the left hand side of the device with no padding applied.

If you then close the menu, and re open it, only then does it apply the padding.

I posted a video of the issue on the Elementor Community on Facebook, you can see the video here - https://www.facebook.com/604193780/videos/10158985223373781/

### To reproduce:
It happens every time. There is no circumstances that specifically causes it.
1. Go on the website on a mobile device 
2. Click the burger icon in the top right (you will see the menu loads with no left padding)
3. Close the menu
4. Re-open the menu (you will now see it now has the correct padding left.

### Expected behavior:
I would expect the padding/styling to work on the first load. It is like there is a delay.

### Screenshots:
https://www.facebook.com/604193780/videos/10158985223373781/
Live link to site: http://liveworks.wearemont.com/backwell

### Isolating the problem:

- [X] This bug happens with no other plugins activated
- [X] This bug happens with a default WordPress theme active
- [X] I can reproduce this bug consistently using the steps above

### WordPress version:
5.6.1

### Elementor version:
3.1.1

**Comment by pratikshasaman** [comment]
Hello @adamjh22,

Thanks for contacting us!

Kindly use the below CSS, it will help you to fix the issue.

```
@media (max-width: 1024px) {
    nav.hfe-nav-menu__layout-horizontal.hfe-nav-menu__submenu-arrow.hfe-dropdown{
        left: -225px !important;
    }
}
```
I hope this helps.

Please do not hesitate to get back to us if you still face any hurdles.

Have a great day ahead!

Regards,
Pratiksha Samane

**Comment by pratikshasaman** [comment]
Hello,

We are closing this query as we did not hear back from you. I hope the CSS provided helped you.

Please do not hesitate to get back to us if you still face any hurdles.
