### ISSUE TITLE
Last Menu Item - When switching to phone and back disapears

### ISSUE THREAD

**Issue by noxerr** [brainstormforce/header-footer-elementor#348]
When you set the last menu item as button, and then switch to phone version and back to desktop, it's not a button anymore

It should be a button in desktop no matter what you do 

### WordPress version:
5.6

### Elementor version:
3.1

**Comment by pratikshasaman** [comment]
Hello @noxerr,

Thank you for bringing this to us!

This issue is already listed in our tasks. We will ship the fix in our upcoming update.

Let us know if we can help with anything else.

Have a great day ahead!

Regards,
Pratiksha Samane

**Comment by pratikshasaman** [comment]
Hello @noxerr,

We have fixed this issue with EHF v1.5.9. Please update EHF to the latest version.

Let us know if we can help with anything else.

Have a great day ahead!
