### ISSUE TITLE
The Elementor editor does not load 

### ISSUE THREAD

**Issue by Insitefuljay** [brainstormforce/header-footer-elementor#349]
Hi, the loader wont load the interface. 
<img width="1193" alt="Screen Shot 2021-02-22 at 2 25 51 PM" src="https://user-images.githubusercontent.com/79486282/108783039-8fb05280-7521-11eb-9c71-6fc46fee05f5.png">

**Comment by Nikschavan** [comment]
@Insitefuljay - Can you please open a support request from this form - https://wpastra.com/support/free-support/

GitHub issues are reserved for the development of the plugin.
