### ISSUE TITLE
FlyOut layout only for mobile

### ISSUE THREAD

**Issue by mammadkoma** [brainstormforce/header-footer-elementor#350]
Hello and thank you for your great plugin.
I use your Navigation Menu by elementor , How wen can use FlyOut layout only for mobile?
When we change display mode to mobile and set layout to FlyOut , Desktop mode change to FlyOut too , but we want select Horizontal for desktop.

**Comment by pratikshasaman** [comment]
Hello @mammadkoma,

Apologies for the delay in response!

We are glad you liked the Elementor - Header, Footer, and Blocks Template plugin. 

Using the navigation menu widget, you will be able to select a single layout. We do not have an option to convert the horizontal layout into a flyout layout onto the responsive devices.

But Elementor, by default, provides a responsive option to the widget, using which you can hide the widget on the responsive devices as per your choice.
Please refer to this screenshot - https://a.cl.ly/E0u9N1pN.

For this, you will need to use two navigation menus on a page. One is with a horizontal layout, and another with a flyout layout. Hide horizontal on responsive devices and flyout layout from the desktop.

Please refer to this video - https://a.cl.ly/2NuEQLnm.

I hope it helps.

Please let us know if you have any further queries.

Regards,
Pratiksha Samane

**Comment by pratikshasaman** [comment]
Hello,

We are closing this query as we did not hear back from you. I hope the step provided helped you.

Please do not hesitate to get back to us if you still face any hurdles.

**Comment by mammadkoma** [comment]
Thank you
