### ISSUE TITLE
Header not visible or looks different on other pages

### ISSUE THREAD

**Issue by Chris-fNf** [brainstormforce/header-footer-elementor#354]
Hello, I am currently creating a new website for my hobby and struggleing with your plugin "Elementor – Header, Footer & Blocks Template"

after creating the header, it looks different between the pages in my website or does not appear. I also emptied the Cache with "WP Fastest Cache" which does not show any improvement
I am using ELEMENTOR for free on ASTRA Theme.

I am very new in this so apologiess, if I may ask stuppid questions
Can you help on this issue?

Many thanks in advance

Cheers
Christian

**Comment by pratikshasaman** [comment]
Hello Chris-fNf,

Thanks for writing to us!

As of now, we are not able to reproduce this issue at our end. Would you be able to kindly provide me more details so I can help you accurately?
﻿
Here are some hints:
﻿
= Could you please attach screenshots as possible.
= If possible, please record a screen capture video of the steps before seeing the issue.

That will help greatly.

Looking forward to hearing from you soon.

**Comment by pratikshasaman** [comment]
Hello,

We are closing this query as we did not hear back from you. Please do not hesitate to get back to us if you still face any hurdles.
