### ISSUE TITLE
elementor breakpoint settings get not recognized in HFB navigation menu block

### ISSUE THREAD

**Issue by vollyimnetz** [brainstormforce/header-footer-elementor#374]
### Describe the bug:
The menu widget of the plugin do not use the breakpoints defined in elementor (free version).

### To reproduce:
1. Set the breakpoints in elementor settings (site settings > Layout > Breakpoints tab) i.e. to 760px width for mobile.
2. Add a Header-Footer-Block for the Header (settings entire website).
3. Add an HFB "Navigation Menu" Block inside the entry.
4. Set the responsive breakpoint of the menu (HFB-Block) to mobile.
5. Change the preview to tablet size or adjust the preview size to above 760px -> the menu is still in mobile mode and will only go to normal mode above 767px. 

### Expected behavior:
The settings from the elementor settings page is recognized and the CSS is changed accordingly.
So in preview mode "tablet size" (i.e. 761px) the normal mode is used - if the mobile mode is set to display size "mobile" instead of "tablet".

### WordPress version:
5.7.2

### Elementor version:
3.2.3

**Comment by sushmak02** [comment]
Hello Vollyimnetz,

Thanks for writing to us!

The Elementor breakpoints can be changed from Elementor settings. Currently, these breakpoints are not accessible in the static CSS files. 
So we have added some custom CSS for the Navigation menu at the default breakpoint values like 767px for mobile and 1024px for tablet.

To change this you will need to override the required CSS with custom CSS by adding your breakpoints. Let me know if you need any help in doing that. You can open a ticket here - https://ultimateelementor.com/contact/ for adding custom support.

**Comment by vollyimnetz** [comment]
Hi @sushmak02,
thank you for responding. Is these planed to implement in the near future?

I currently use a workarround where i have 3 different rows for each breakpoint dimensions which works fine. But would be nice to have this fixed in some way. Would also be ok if it is adjustable via filter/action. But to have no way to adjust the breakpoints of the navigation is a little bit odd.

**Comment by sushmak02** [comment]
Hello @vollyimnetz,

Currently, this can not be managed via a custom hook.

We will take a step further and will contact Elementor regarding this. If possible we will surely add support for this in our future updates.

Thank You!
