### ISSUE TITLE
Disabling the active link effect

### ISSUE THREAD

**Issue by braincrush** [brainstormforce/header-footer-elementor#376]
I have a page with nav menu where i have mixture of anchor links and page links, at the moment the on hover link effect or even typography for on hover is automatically applied to the active links and that causes obvious problems with the look of the navbar ( 3 links are in active state because they call for the homepage#anchor, i think we should be able to disable that.
Unless of course there is a way of doing that and i just cannot find it?

![Screenshot 2021-06-01 at 10 51 18](https://user-images.githubusercontent.com/2714475/120304214-7e68a600-c2c7-11eb-9f17-5ab53f5f9c78.png)

**Comment by pratikshasaman** [comment]
Hello @braincrush,

Apologies for the delay!

We tried to create the same scenario and seems to be working fine at our end. Please check this video - https://share.bsf.io/GGuW8o8B

Could you please send us your site URL and steps to reproduce the issue at our end? That will help greatly.

Looking forward to hearing from you.

**Comment by braincrush** [comment]
thank you for looking into it, i think the problem is when i have mix of anchors and link in the nav menu, anchors on their own just #anchor work fine however because i have to access those anchors from different page i have to link fullurltohomepage#anchor and that is what makes the website think all 3 are the same page.

**Comment by pratikshasaman** [comment]
Hello @braincrush,

Thank you for the detailed information!

Yes, the issue is reproducible at our end if we use fullpagelink#anchor. Although, the custom solution is not available. We will get this fix in an upcoming update.

I hope the information will help. Let us know if we can help with anything else.

Have a great day ahead!

**Comment by braincrush** [comment]
amazing, thank you!
