### ISSUE TITLE
First menu element not showing in certain Safari-iOS devices

### ISSUE THREAD

**Issue by mercedeschirico** [brainstormforce/header-footer-elementor#380]
### Describe the bug:
I'm working on this website, using Header, Footer & Blocks plugin.
I used the Navigation Menu element, and everithing looked good until I tested it on some iPad and iPhone devices (you can see which devices in the photos below).
The problem is this: in those devices, the first menu item doesn't show.
I had to change the nav-menu on the actual pages while this issue persists, but I'm not satisfied with the other options I found.
I would really prefer to solve this bug and use your navigation menu.

### To reproduce:
This is a test page, just to reproduce the isue: https://sergiostudiony.com/test-orig/
The other pages of the site use a different menu plugin.

### Expected behavior:
![movil_bien](https://user-images.githubusercontent.com/85835968/121812914-39862d00-cc40-11eb-8464-c38cf1027bb0.png)

### Screenshots:
![WhatsApp Image 2021-06-10 at 14 00 46 (1)](https://user-images.githubusercontent.com/85835968/121812936-47d44900-cc40-11eb-81f4-2bc204c8d47b.jpeg)
![WhatsApp Image 2021-06-10 at 14 00 46](https://user-images.githubusercontent.com/85835968/121812938-486cdf80-cc40-11eb-896e-9a8875c03098.jpeg)

### WordPress version:
5.7.2

### Elementor version:
3.2.4

### Elementor - Header, Footer & Blocks version:
1.5.9

**Comment by sushmak02** [comment]
Hello @mercedeschirico,

Thanks for writing to us!

I checked for a similar issue on different iPhone and iPad devices. As of now, we are not able to reproduce this issue at our end. Would you be able to kindly provide me more details so I can help you accurately?

Here are some hints:
﻿
- Could you please share the iPhone or iPad version?
- Add a new menu widget and check if the same issue appears.

That will help greatly.

Looking forward to hearing from you soon.

**Comment by mercedeschirico** [comment]
Hello @sushmak02.
I'm sorry I couldn't write sooner

I don't have access to the actual devices which show this problem.
But my client (the website owner) tested it using devices avaliable in some store. He lives in New York, and I live in Uruguay, so it's impossible for me to go to that same devices.
Anyway, the info I have on that devices is what is shown on the photos I uploaded. But I can say I tested using the free trial from [https://www.browserstack.com/live](https://www.browserstack.com/live) (they say they test on real devices), and I was able to reproduce this error on this devices:

iPhone 12 Mini
iPhone 12 Pro Max
iPhone 12 Pro
iPhone 12
iPhone 11 Pro
iPhone 11
iPhone 11 Pro Max
I always tested using Safari.

Right now, You can check this page: https://sergiostudiony.com/test2/

I added other menu widgets, selecting both the same menu or another, and the problem persists. 

Thank you in advance for your help!

**Comment by gaurav-jangam** [comment]
Hello @mercedeschirico,

Thanks for writing to us!

I checked for a similar issue on different iPhone and iPad devices. As of now, we are not able to reproduce this issue on our end.

I have checked your website( https://sergiostudiony.com/test2/ ) at [browserstack](https://www.browserstack.com/live ).

Please see the following screenshots:

1. iPhone 12 Mini - https://d.pr/i/Xx5Z50
2. iPhone 12 Pro Max - https://d.pr/i/JkbOiI
3. iPhone 12 Pro - https://d.pr/i/T1ABav
4. iPhone 12 - https://d.pr/i/4Nj3a4
5. iPhone 11 Pro - https://d.pr/i/TYyITM
6. iPhone 11 - https://d.pr/i/3scpbl
7. iPhone 11 Pro Max - https://d.pr/i/7Vw7XI

Looking forward to hearing from you soon.

**Comment by vijetaR** [comment]
Hi @mercedeschirico As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin or any other matter.
