### ISSUE TITLE
Elementor Header & Footer Builder - location Issue After Recent Update

### ISSUE THREAD

**Issue by Galit12** [brainstormforce/header-footer-elementor#389]
### Describe the bug:
After the last update, my footer changed position on the website, instead of being at the bottom of the website, now its in the middle. 

### To reproduce:
I tried to delete the footer and re-create it, the issue still remains.

### Expected behavior:
The footer should be kept at the bottom of the website.

### Isolating the problem:
![image](https://user-images.githubusercontent.com/86292129/122898238-65499700-d353-11eb-8ac9-ecd4e60871f7.png)

- [ ] This bug happens with a default WordPress theme active

### WordPress version:
5.7.2

### Elementor version:
v3.2.5

**Comment by eemeli05** [comment]
I have the same issue

**Comment by YouthDestinationIASPCS** [comment]
I have also same (https://youthdestination.in/)

**Comment by akos123akos** [comment]
Hi, I have the exact same problem, I used a backup to solve it, now the older version is still working fine but if u refresh the plugin it brakes my website.
Any tips to solve this, im using Astra theme with a woocommerce combo.
Cheers

**Comment by yebda** [comment]
Salut a tous, 
Personnellement, c'est le haut de ma page qu'il couvre avec une couleur unit.
Quelqu'un sait ou je pourrais télécharger la version 1.5.9 ?

**Comment by Galit12** [comment]
Hi, is that mean the bug is fixed? if so, when will you release the updated version?

**Comment by sushmak02** [comment]
We have released version 1.6.1 with a fix for the footer placement issue. Please update to the latest!

**Comment by Galit12** [comment]
Hi, I updated to version 1.6.1 but now it doesn't work at all. I am creating the footer, publish it, but is doesn't appear on the website...

**Comment by pratikshasaman** [comment]
Hello @Galit12,

Could you please check if flushing the permalinks helps? -- https://wpastra.com/docs/how-to-refresh-wordpress-permalinks/.

If this information doesn't help, please deactivate all plugins temporarily and see if that solves the problem. Then, activate plugins one by one to see which plugin is causing the problem.

Let us know how it goes.

**Comment by Galit12** [comment]
No, nothing helped, I even deleted and re-installed the plugin. 
Nothing helped.

**Comment by Nikschavan** [comment]
@Galit12 Can you share link to your website so that I can debug this?

**Comment by Galit12** [comment]
Hi, sorry I just removed the plugin and worked with other plugin
