### ISSUE TITLE
Wrong return type in views_edit-elementor-hf filter

### ISSUE THREAD

**Issue by Djennez** [brainstormforce/header-footer-elementor#394]
### Describe the bug:
Some logic in `HFE_Settings_Page::hfe_settings()` will short-circuit the `views_edit-elementor-hf` filter, causing problems down the line.

The `hfe_settings()` function filters the `views_edit-elementor-hf` filter and is supposed to return an array as `$value`. However, some logic that checks for subscription status and or pop-up dismissal status causes the function to return `False` instead of an array here:

https://github.com/brainstormforce/header-footer-elementor/blob/ab5ef942b236d32e6de761b1bcecd8b4f1e9aefc/inc/class-hfe-settings-page.php#L108-L109

When this logic is triggered, it will cause the table filters to not be visible:
![image](https://user-images.githubusercontent.com/34372510/123785461-d996b400-d8d8-11eb-85da-cdebcab8d901.png)

However, because an array is expected as a value from this filter, any plugins that filter this value after passing through this logic will cause other unwanted behavior. In our case, with Yoast SEO (16.5) installed, a fatal occurs.

### To reproduce:
1. Install Elementor (3.2.5) and HFE (1.6.1)
2. This step I am unsure of, as I could not find how to get this data in my database. But if your user has meta_options like this: meta_key -> `hfe-popup`, meta_value -> `dismissed` it will trigger. I guess you might now better how to get to that result 😉 
3. Visit the `Appearance -> Elementor Header & Footer Builder` page.
4. Notice the filter values (All | Published | et cetera) are unavailable.
5. If you have Yoast SEO 16.5 installed at this point, a fatal error will occur.

### Expected behavior:
- I expect the filter to return an array, so that it doesn't cause issues down the line.

### Screenshots:
Added in the description.

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
  - Unless Elementor does not count as another plugin.
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
5.7.2

### Elementor version:
3.2.5

**Comment by sushmak02** [comment]
Hello @Djennez,

Thank you for contacting us!

Yes, we have found this issue earlier and fixed it in our development version. This is in the testing phase.

We will release a patch for this in our coming update.

Thank you for all your efforts in reporting this to us!

**Comment by sushmak02** [comment]
Hello @Djennez,

We have released a fix for this issue in version 1.6.2. 

Update Elementor Header & Footer Builder to its latest version.

Thank You!
