### ISSUE TITLE
Blank page when deactivating header-footer plugin

### ISSUE THREAD

**Issue by elsdeniep** [brainstormforce/header-footer-elementor#425]
Hi.
We have used the plugin for some time. It served us well. Recently we have purchased Elementor Pro. That version of Elementor has it's own header and footer builder. 

### Describe the bug:
We use Elementor PRO headers and footers builder.
When deactivating the Brainstormforce Elementor Header & Footer Builder plugin, website is showing a blank page as in an entirely white page: no content, no header, no footer.

### To reproduce:
From the wp backend go to:
Dashboard -> Plugins -> Elementor Header & Footer Builder -> Deactivate

### Expected behavior:
The Elementor header and the page content is being displayed.
Instead, nothing is being displayed.

### Isolating the problem:

- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
Last version

### Elementor version:
Elementor Pro. Last version

Thanks in advance for suggestions to solve this issue.

**Comment by swapnilde** [comment]
Hello @elsdeniep,

Thanks for writing to us!

I tried the same scenario at our end. But, we are not able to reproduce this issue at our end. Would you be able to provide me with more details so I can help you accurately?

Besides that, you can try the below steps and check this resolves your issue:

1. Please try switching to a Wordpress default theme or any other, like Twenty Seventeen, and check whether the issue persists. If yes, then it is not the theme that is causing the error.
2. Deactivate all plugins temporarily and see if that solves the problem. Then, activate plugins one by one to see which plugin is causing the problem.

Even after all the above steps if your issue still does not resolve then we will need to take a look at your website.
For that, you can open a support ticket from our UAE's website - https://ultimateelementor.com/support/open-a-ticket/

**Comment by elsdeniep** [comment]
Hi @swapnilde ,
After some more testing and the help of the Elementor team, we have ununstalled the AddFunc Head & Footer Code plugin.
This has solved the issue.

Thanks for your help.

Best regards,
Els
