### ISSUE TITLE
Submenu click on One Page Scroll working but reloads the page

### ISSUE THREAD

**Issue by rolodoom** [brainstormforce/header-footer-elementor#442]
### Describe the bug:

On a one page scroll site, submenu link is scrolling to the section and reloading the page.
I don't really now if it's a bug but is kind of not expected.
### To reproduce:

1. Install Elementor and Elementor Header & Footer Builder (HFE) plugins
2. Install Hello Elementor Theme
3. Create a page with Elementor (Full Width Template) and multiple sections
4. Create a Menu
5. Create a Header with HFE and assign the menu
6. Open page
7. Scroll working and page reloding

### Expected behavior:

Scroll to section when click on submenu item and NOT refreshing the page.
### Isolating the problem:

- [x] This bug happens with no other plugins activated, only Elementor active.
- [x] This bug happens with Hello Elementor theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

5.8.2
### Elementor version:

 3.4.8

**Comment by swapnilde** [comment]
Hello @rolodoom,

Thank you for getting in touch with us.

We tried creating a similar scenario and tested the one-page menu. Everything worked fine at our end.
It's very hard to determine the cause of the issue without looking into your site. I would request If you could share the URL of your site so that we can take a look at it and debug the issue.

Waiting for response.

**Comment by rolodoom** [comment]
Hello @swapnilde thanks for your answer.

Here is a sample site with the problem http://45.79.42.197/

![Screenshot_20211122_132554](https://user-images.githubusercontent.com/61945227/142915406-a5d133ce-fa2a-4511-a81e-b8503e395acc.png)

The items outside de sub-menu, work as expected. no problem here, but the items on the sub-menu are reloading the page, I think they're not supposed to do that.

Waiting for your response

**Comment by gaurav-jangam** [comment]
Hello @rolodoom,

Thank you for getting in touch with us.

We tried creating a similar scenario and tested the one-page menu. Everything worked fine at our end.
Please check the screencast - https://d.pr/v/7tvBnu

Waiting for a response.

**Comment by rolodoom** [comment]
Hello there. Thanks for your response. I tested everything again, re-installed and everything is fine.

WP  5.9.3
Elementor  3.6.5
