### ISSUE TITLE
Remove [maximum-scale=1] 

### ISSUE THREAD

**Issue by NicolasBernaux** [brainstormforce/header-footer-elementor#456]
Allow user to scale the page for a better accessibility.

In `header-footer-elementor/themes/default/hfe-header.php` just remove `maximum-scale=1`

**Comment by swapnilde** [comment]
Hello @NicolasBernaux,

Thanks for submitting that suggestion. I will forward your query to our developers for consideration.
The team will review and fix this if necessary and release a patch for this in our future update.

If you have anything else we can help you with do let us know.
We appreciate your recommendation.

**Comment by gaurav-jangam** [comment]
Hello @NicolasBernaux,

We have already added a task for it to our to-do list.

Right now, I could not provide the exact ETA for this, but we will definitely fix this issue in our next update.

Your patience and co-operation are highly appreciated.
