### ISSUE TITLE
header and footer not showing in mobile

### ISSUE THREAD

**Issue by AlejandroJoseph** [brainstormforce/header-footer-elementor#512]
Hi, for some reason, elementor header & footer stoped working in mobile format. It shows ok in desktop -even when previewing in mobile format- but no directly in mobile. There was no problem some months ago. I've tried different solutions read in forums, nothing seem to work. 

### Screenshots:
![header bien en desktop](https://user-images.githubusercontent.com/82245439/162491087-7cf5ca02-7f57-40d9-a396-44d1847bfd10.jpg)

![Header bien en mobile desktop](https://user-images.githubusercontent.com/82245439/162491151-a4e16a77-3ec4-489e-8dfc-ca12886adc3d.jpg)

![configuración header](https://user-images.githubusercontent.com/82245439/162491185-c6db30f7-857b-4186-b649-6107dee298fd.jpg)

![header no aparece en mobile](https://user-images.githubusercontent.com/82245439/162491222-a74bc0f2-8135-44c3-add8-93c8a1770b03.jpeg)

### Expected behavior:
To see the header & footer in mobile version. 

### WordPress version:
5.9.3 running Hello Elementor theme.

### Elementor version:
Pro

**Comment by AlejandroJoseph** [comment]
Hi! Issue is now fixed. The problem was that in the Header & footer User role parameters I had Administrator and not All, thereby, since I was logged in the desktop version I could see it, but when trying to see it on mobile I couldn't.

**Comment by murshed** [comment]
We are pleased to hear that the issue has been resolved and that you are now able to continue work.
