### ISSUE TITLE
Can not edit header with elementor

### ISSUE THREAD

**Issue by Wescreator2** [brainstormforce/header-footer-elementor#519]
### Describe the bug:
I should be able to edit header in elementor after I've installed the header and footer plugin. However I receive a error.

### To reproduce:

1. Go to add new template
2. choose  type of template, display and user roles. 
3. Click on 'update'
4. Then click on edit with elementor.
5. See error

### Expected behavior:
I expected elementor to open so that I can edit the header

### Screenshots:
![error](https://user-images.githubusercontent.com/103785614/163635057-150644fa-0e6c-42cc-855e-f8bc2a69e3ed.jpg)

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active

- [ ] I can reproduce this bug consistently using the steps above

### WordPress version:
Latest

### Elementor version:
if applicable

**Comment by gaurav-jangam** [comment]
Hello @Wescreator2,

Thank you for getting in touch with us.

We tried creating a similar scenario and tested it. Everything worked fine at our end.

Please check the following DOC Link It might help :
https://elementor.com/help/how-to-fix-the-preview-could-not-be-loaded-error/

After following the above steps still the error persists then open a ticket - https://brainstormforce.com/open-a-ticket/

Waiting for a response.

**Comment by vijetaR** [comment]
Hi @Wescreator2 As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin or any other matter.
