### ISSUE TITLE
Menu problems after installing Elementor 3.11.1 

### ISSUE THREAD

**Issue by Setita** [brainstormforce/header-footer-elementor#655]
I am using Elementor Header & Footer Builder version 1.6.13. After installing new version of Elementor (3.11.1 ), the Navigation Menu stopped to display the menu at all. When I reinstalled Elementor to previous version. Menu got back, but i couldn't format it properly (no spaces between elements) and moreover on mobile version, the mobile icon stopped to display menu elements anymore.

**Comment by vijetaR** [comment]
Hi Setita,

To help us resolve your issue efficiently, we kindly request that you open a support ticket. 
When creating your ticket, please provide us with as much detail as possible about the issue you are experiencing. This will help us understand your problem better and assist you in finding a solution more quickly. Be sure to include any error messages, steps to reproduce the issue, and any relevant screenshots. In addition, if you have any credentials or login information related to the issue, please share them with us securely.

Thank you for your cooperation in this matter. We look forward to assisting you.

**Comment by ValentinGratz** [comment]
> Hi Setita,
> 
> To help us resolve your issue efficiently, we kindly request that you open a support ticket [LINK](https://ultimateelementor.com/support/). When creating your ticket, please provide us with as much detail as possible about the issue you are experiencing. This will help us understand your problem better and assist you in finding a solution more quickly. Be sure to include any error messages, steps to reproduce the issue, and any relevant screenshots. In addition, if you have any credentials or login information related to the issue, please share them with us securely.
> 
> Thank you for your cooperation in this matter. We look forward to assisting you.

Hello,

I don't know if my ticket is related to this bug as well, but can you take a look (I put some technical information there)
ticket: #653

**Comment by vijetaR** [comment]
Hi @Setita, As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.
