### ISSUE TITLE
elements contain focusable descendents

### ISSUE THREAD

**Issue by MGaines2** [brainstormforce/header-footer-elementor#665]
Hello, I hope all is well. I have a website that I'm using the header-footer plugin. The problem is when I test the site in PageSpeed Insights I get a warning that the [aria-hidden="true"] elements contain focusable descendants. 

This warning is appearing on my mobile and is affecting my score. How can I fix the issue?  Thank you

**Comment by vijetaR** [comment]
Thank you for letting us know about the issue you are experiencing. We are already working on a solution, and we will release a patch in the next update. Thank you for your patience and understanding.

**Comment by vijetaR** [comment]
Hi @MGaines2 , We are delighted to inform you that the issue has been successfully resolved. Kindly take a moment to review version 1.6.14, where we have implemented a patch to address the issue.
