### ISSUE TITLE
Nav menu: html validation error - tabindex  inside element with the attribute role=button

### ISSUE THREAD

**Issue by palansher** [brainstormforce/header-footer-elementor#690]
Thank you for the cool plugin!

### Describe the bug:

The problem is tabindex in
```  <i aria-hidden="true" tabindex="0" class="fas fa-align-justify"></i> ```

Html validators say:
Error: An element with the attribute tabindex must not appear as a descendant of an element with the attribute role=button

It is located in  Navigation Menu:
```
<div class="elementor-widget-container">
   <div class="hfe-nav-menu hfe-layout-horizontal hfe-nav-menu-layout horizontal hfe-pointer__underline hfe-animation__drop-in" data-layout="horizontal">
      <div role="button" class="hfe-nav-menu__toggle elementor-clickable" aria-haspopup="true" aria-expanded="false">
         <span class="screen-reader-text">Меню</span>
         <div class="hfe-nav-menu-icon">
            <i aria-hidden="true" tabindex="0" class="fas fa-align-justify"></i>					
         </div>
      </div>
      <nav class="hfe-nav-menu__layout-horizontal hfe-nav-menu__submenu-arrow hfe-dropdown" data-toggle-icon="<i aria-hidden=&quot;true&quot; tabindex=&quot;0&quot; class=&quot;fas fa-align-justify&quot;></i>" data-close-icon="<i aria-hidden=&quot;true&quot; tabindex=&quot;0&quot; class=&quot;far fa-window-close&quot;></i>" data-full-width="yes">
         <ul id="menu-1-4eb2cab" class="hfe-nav-menu">
            <li id="menu-item-75" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-22 current_page_item parent hfe-creative-menu"><a href="https://gurevich-taxopark.ru/" class="hfe-menu-item">Главная</a></li>
            <li id="menu-item-101" class="menu-item menu-item-type-post_type menu-item-object-page parent hfe-creative-menu"><a href="https://gurevich-taxopark.ru/kontakty/" class="hfe-menu-item">Контакты</a></li>
            <li id="menu-item-344" class="menu-item menu-item-type-custom menu-item-object-custom parent hfe-creative-menu"><a href="https://gigakassa.ru" class="hfe-menu-item">Личный кабинет</a></li>
            <li id="menu-item-1932" class="menu-item menu-item-type-custom menu-item-object-custom parent hfe-creative-menu"><a href="https://grudkolesom.ru/" class="hfe-menu-item">Наша СТО</a></li>
         </ul>
      </nav>
   </div>
</div>
```

### To reproduce:

insert navigation menu with default settings
The default response/breakpoint  will show mobile icon with strange "tabindex"

### Expected behavior:
no html validator error

### Isolating the problem:
just set breakpoint to 'none' in Nav menu settings

- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.2.2

### WordPress Theme:
Hello Elementor https://github.com/elementor/hello-theme

### Elementor version:
v3.13.4

### Elementor Header & Footer Builder version:
1.6.14

**Comment by vijetaR** [comment]
Hi @palansher, thank you for letting us know about the error. We really appreciate your help in bringing it to our attention. Further to that, we have successfully reproduced the issue on our end and have taken note of the problem. The fix will be resolved as soon as possible.

**Comment by palansher** [comment]
For any case I am just inform that the issue still exists in new versions. I understand that it takes time and I will be patient.

**Comment by vijetaR** [comment]
Hi @palansher, We are delighted to inform you that the issue has been successfully resolved. Kindly take a moment to review version 1.6.15, where we have implemented a patch to address the issue.
