### ISSUE TITLE
How Can We Continue Using a Theme's Header After Creating a Footer Using EH&FB?

### ISSUE THREAD

**Issue by mikeglenn** [brainstormforce/header-footer-elementor#701]
Hello, I rewrote the website footer in staging using Elementor Footer and Header Builder, then realized it also hides the original theme header. We want to keep using the theme's header, but it is blocked by EH&FB. Is it possible to bypass this behavior to allow the theme's header to display? 

If this hybrid mode is not possible, how can I restore the original theme header and footer? When I deactivate EH&FB the original header is still blocked. Will uninstalling restore everything to it's original state?

Website: staging.releaftreats.com   (remove staging. to see the live website with theme header still visible)

As you can see, we currently have no header/menu at all in staging! I feel Elementor (even with Pro license) is frustratingly limited for recreating the themes website header. (Theme is Vapier)

**Comment by mikeglenn** [comment]
I discovered Elementor Pro Theme Builder also blocks display of the theme's header or footer. So, even uninstalling Elementor Footer and Header Builder will not solve this issue if you subsequently start building and header and/or footer in Elementor's Theme Builder. Feel free to close/ignore this issue.

**Comment by vijetaR** [comment]
Hi @mikeglenn As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.
