### ISSUE TITLE
Extra closed </div> generated by Version: 1.6.14

### ISSUE THREAD

**Issue by palansher** [brainstormforce/header-footer-elementor#703]
Hello!

You made superb plugin, but buggy yet, related to html markup.

Plugin version: 1.6.14
Problem: 
extra </div> appears in (marked yellow)

![image](https://github.com/brainstormforce/header-footer-elementor/assets/24850253/c403d9f8-95d2-4f65-930e-14cc59e77b5c)

You ca check it i.e. by http://www.tormus.com/tools/div_checker service, entering URL: 
https://blog.palansher.ru/elementor-hf/default-footer/ 

OR

check whole site https://blog.palansher.ru in https://validator.w3.org/ 

### Isolating the problem:

The problem decappers after disabling this plugin.
There are no custom html code in my footer section.

### WordPress version:
6.2.2

### Elementor version:
3.14.1

**Comment by palansher** [comment]
Hello! I would glad to open support ticket. 
But the support site offers me only 
-  Premium Support

But header-footer-elementor is not a premium product and is not on product list of support wizard.
Please advise, how to create support ticket in my case.

**Comment by vijetaR** [comment]
Hi @palansher I apologize for the inconvenience caused by the incorrect link provided earlier. To open a ticket, kindly use the following link: [HERE](https://brainstormforce.com/open-a-ticket/). If you encounter any issues or have further questions, please don't hesitate to reach out.

**Comment by palansher** [comment]
Thank you. Ticket 424897 is created.

**Comment by vijetaR** [comment]
Hi @palansher We wanted to inform you that the issue you reported in your ticket has been successfully resolved. Our team has taken care of this matter and your website should be free from the issue you encountered.
