### ISSUE TITLE
Missing alt image text for default logo affect SEO and accesibility

### ISSUE THREAD

**Issue by julisssax** [brainstormforce/header-footer-elementor#724]
When a custom logo is selected, the alt tag alt text works correctly, but if a custom logo is not selected, and the default site logo is used instead, the plugin does not display the site logo alt text.

### To reproduce:
1. Go to 'Edit with Elementor / Header.'
2. Click on the logo.
3. In left panel in Logo set the option "Custom Image" to "No/Off"
4. Clic in Update.
5. Check in live website the missing alt attribute for the logo. 

### Expected behavior:

If the header use the default logo, must be show the alt text of the default logo, but not work. 

### WordPress version:
6.3.1

### Elementor version:
3.16.1

### Header and footer for elementor version:
1.6.16

**Comment by vijetaR** [comment]
Thank you @julisssax for letting us know about the issue you are experiencing. We are working on a solution, and we will release a patch in the next update. Thank you for your patience and understanding.

**Comment by vijetaR** [comment]
Hi @julisssax, we have resolved the issue mentioned above. We will include this fix in our upcoming update.
