### ISSUE TITLE
Last update to 1.6.18 broke my Header and Footer due to incorrect rendering of SVG image and the menu button

### ISSUE THREAD

**Issue by ryanskystack** [brainstormforce/header-footer-elementor#745]
Hi team,

Could you please check it for me that When I update  the Elementor Header & Footer Builder to the Version 1.6.18,

our header in our website crashes:

the logo with a message:

/*! elementor - v3.17.0 - 08-11-2023 */ .elementor-widget-text-editor.elementor-drop-cap-view-stacked .elementor-drop-cap{background-color:#69727d;color:#fff}.elementor-widget-text-editor.elementor-drop-cap-view-framed .elementor-drop-cap{color:#69727d;border:3px solid;background-color:transparent}.elementor-widget-text-editor:not(.elementor-drop-cap-view-default) .elementor-drop-cap{margin-top:8px}.elementor-widget-text-editor:not(.elementor-drop-cap-view-default) .elementor-drop-cap-letter{width:1em;height:1em}.elementor-widget-text-editor .elementor-drop-cap{float:left;text-align:center;line-height:1;font-size:50px}.elementor-widget-text-editor .elementor-drop-cap-letter{display:inline-block}

And the hamburger bar(menu button) can't work.

We're using the following plugins:

Elementor: Version 3.17.3
Elementor Header & Footer Builder: Version 1.6.17
Elementor Addon Elements: Version 1.12.9
Premium Addons for Elementor: Version 4.10.15

Thanks so much!

I'm looking forward to your prompt reply.

Kind Regards

**Comment by vijetaR** [comment]
Apologies for the trouble. The issue you encountered in the Elementor Header & Footer Builder plugin has been addressed in the latest update, version 1.6.19. Kindly install this update to resolve the problem. Thank you for your understanding, and please let us know if you encounter any further issues after updating!

**Comment by jacktnp** [comment]
> Apologies for the trouble. The issue you encountered in the Elementor Header & Footer Builder plugin has been addressed in the latest update, version 1.6.19. Kindly install this update to resolve the problem. Thank you for your understanding, and please let us know if you encounter any further issues after updating!

I found issue more. In Mobile menu Menu not render It's show plain text instead html render help please. Thanks.

**Comment by boypipe** [comment]
> > Apologies for the trouble. The issue you encountered in the Elementor Header & Footer Builder plugin has been addressed in the latest update, version 1.6.19. Kindly install this update to resolve the problem. Thank you for your understanding, and please let us know if you encounter any further issues after updating!
> 
> I found issue more. In Mobile menu Menu not render It's show plain text instead html render help please. Thanks.

Yup same. This issue happens to Header/Hamburger menu that uses "Content>Layout>Flyout"

**Comment by vijetaR** [comment]
Hi @ryanskystack,@jacktnp @boypipe, As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.
