### ISSUE TITLE
Retina Image link does not work

### ISSUE THREAD

**Issue by digimarkup** [brainstormforce/header-footer-elementor#749]
I should be able to click on the image and go to the URL that was saved for the image.

### To reproduce:
Add the Retimna Image to your header
Choose custom URL for the link option
Enter a URL and click update.
Visit a page that uses the header and click on the image.

### Expected behavior:
I should be able to click the image and go to the custom URL.

### Screenshots:
Here's the [link to a screenshot](https://www.dropbox.com/scl/fi/guwzua3qwd8d4u5mlrhqb/retina-image.png?rlkey=amdo37pvzn46bihlz5k4zhkdv&dl=0) showing the a tag missing the href attribute

### Isolating the problem:
 This bug happens with no other plugins activated
 This bug happens with a default WordPress theme active
 I can reproduce this bug consistently using the steps above

WordPress version: 6.4.2
Elementor version: 3.18.2
Elementor Header & Footer Builder 1.6.21

**Comment by vijetaR** [comment]
Apologies for the trouble. The issue in the Elementor Header & Footer Builder plugin has been fixed in the latest update (version 1.6.22). Please install this update to resolve the issue. Let us know if you face any more issues after updating. Thank you!
