### ISSUE TITLE
Image flag not working on menu when update to 1.6.23

### ISSUE THREAD

**Issue by rolodoom** [brainstormforce/header-footer-elementor#756]
### Describe the bug:

Image flag not working on menu using Polylang

### To reproduce:

1. Update from 1.6.22 to 1.6.23
2. Re activate the plugin
3. Image flag stop working. Give 404 error image not found.

### Expected behavior:

Image flag should be shown on the menu

### Screenshots:

Before update:
![Screen Shot 2024-01-09 at 16 04 19](https://github.com/brainstormforce/header-footer-elementor/assets/61945227/41b7b7fe-2cfe-4233-8659-e48874541d08)

After update:
![Screen Shot 2024-01-09 at 16 06 19](https://github.com/brainstormforce/header-footer-elementor/assets/61945227/9b0b5db4-22b5-499f-ab4a-707d96d5340a)

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

Wordpress: 6.4.2

### Elementor version:

Elementor: 3.18.3
Elementor Header & Footer Builder: 1.6.23
Polylang: 3.5.3

**Comment by vijetaR** [comment]
Hello @rolodoom, we appreciate your prompt notification regarding the error. Thank you for bringing it to our attention. We have successfully replicated the issue on our end and noted the problem. Rest assured, the fix will be resolved as soon as possible.

**Comment by Fera** [comment]
I confirm. I had a similar error.

**Comment by vijetaR** [comment]
Apologies for the trouble. The issue in the Elementor Header & Footer Builder plugin has been fixed in the update version ([1.6.24](https://github.com/brainstormforce/header-footer-elementor/releases/tag/v1.6.24)). Please install this update to resolve the issue. Let us know if you face any more issues after updating. Thank you!

**Comment by rolodoom** [comment]
It's been fixed!!! Great!!
