### ISSUE TITLE
Sub dropdown menu icon not loading

### ISSUE THREAD

**Issue by jaydeepnamera** [brainstormforce/header-footer-elementor#766]
### Describe the bug:
When Elementor Ongoing Experiments Feature Inline Font Icons is Active then dropdown icon is not loading.

### To reproduce:
Go To Elementor > Settings > Features > Inline Font Icons

### Screenshots:
https://prnt.sc/jyMb30Zf4yQ0

### Isolating the problem:
- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a Hello Elementor theme 
- [ ] I can reproduce this bug consistently using the steps above

### WordPress version:
6.4.3

### Elementor version:
3.19.0

**Comment by vijetaR** [comment]
Hello @jaydeepnamera Please change the option to 'Yes' in the settings https://prnt.sc/U-q2YQlpKTlR. If set to 'No' by default, it means the script is turned off. Setting it to 'Yes' ensures that Font Awesome 4 icons work well with Font Awesome 5. This helps everything transition smoothly between the two versions. Hope this helps with the issue. Let me know if you encounter any issue.
