### ISSUE TITLE
After update Elementor version 3.20.0 no Function from Elementor-Header-Footer-Builder 

### ISSUE THREAD

**Issue by mv-tie** [brainstormforce/header-footer-elementor#778]
### Describe the bug:
<After update Elementor version 3.20.0 works with Elementor-Header-Footer-BuilderVers. 1.6.26 the header menu is no longer correct. When you open the homepage, the submenus are briefly expanded and disappear again. The header page can no longer be edited with Elementor, there is an empty screen">

### Screenshots:
<![image](https://github.com/brainstormforce/header-footer-elementor/assets/163127885/5be25710-7151-42d7-9139-21ffea230c30)>

### Isolating the problem:

- [x ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently using the steps above

### WordPress version:
<6.4.3>

### Elementor version:
<3.20.0>

**Comment by mv-tie** [comment]
Addendum: I have restored the data backup earlier, which I made yesterday before the update. After that, the submenus didn't open, but I still couldn't edit the page.
I tried to take a screenshot of the open menu, but it doesn't work. Please have a look at the homepage yourself:
https://test.mv-tiengen.de/
Thanks!

**Comment by vijetaR** [comment]
Hi @mv-tie, We've conducted testing with the latest versions of Elementor Header & Footer Builder on our end, but we haven't encountered the issue you mentioned. However, I was able to open the menu. [Here](https://prnt.sc/f60GoJeG21A3)
To assist you better, could you please open a ticket on our [support portal](https://brainstormforce.com/open-a-ticket/). Kindly provide access to your demo site along with the necessary steps and credentials. This way, we can assist you more effectively.

**Comment by mv-tie** [comment]
Hello ,
I have only given you the homepage link test.mv-tiengen.de so that you can see, when you call up the page, that the submenus open briefly and then disappear again. The main menu remains visible and you can also use it normally.
 
Here I have made a Foto from the Menü if I load the homepage, you can see in the background faintly the submenus
 
what I can't edit is in the dashboard -> design -> elemtor Header & Footer builder -> header -> edit with elementor
there appears a white monitor like on the screenshot I have uploaded two hours again.
 
 
Does this information help? If not: I don't know how to open a support ticket, please send the appropriate link
![Uploading 20240312_144645.jpg…]()

**Comment by mv-tie** [comment]
Hello Vijeta, Have you been able to take a look at my new inputs from gesetern and do you have an idea how to solve this? I have already publicly announced the launch of the new homepage and of course I want to have a well-functioning layout and not have such weird behaviors of the menu. Therefore, a short-term feedback would be very helpful. Thank you very much. Greetings

**Comment by mv-tie** [comment]
Today there was an Update from Elementor, but it´s always the same. Please give me Feedback. Thanks!

**Comment by vijetaR** [comment]
Hi I have revisited  the site link, menu seems to be functioning well, not seen any weird behaviours . [Screencast](https://www.loom.com/share/25341fd29e3a4dc2a0d3504b8589f028?sid=3a5fc096-662b-4f78-b0a0-4f760edb7280)
To assist you further, could you please create a [support](https://brainstormforce.com/open-a-ticket/) ticket on our website.  Here [screenshot](https://prnt.sc/ocenV3TgR6ZZ) for reference. Add the details further. Also, the link provided above image ain't redirecting to expected. please check. [Here](https://prnt.sc/VLS46qUDSaqn). In the ticket, kindly provide access to your demo/staging  site along with the necessary steps and login credentials. Additionally, if you could attach a screencast explaining the issue, it would greatly help us understand it better.

**Comment by mv-tie** [comment]
hello, I already opened a ticket, now just another one. I reverted the update yesterday, which is why you can't see the error anymore. I just installed the update again. Please take care of the issue in the short term, as the site is not acceptable as it is. Rest see sep. Ticket Thanks

**Comment by Camboa** [comment]
Hello,
I have exactly the same problem.
Were you able to find a solution?

**Comment by ByMarko99** [comment]
New update 1.6.28 same issue again, 1.6.27 worked fine, had to downgrade back to it. The header page can no longer be edited with Elementor, bunch of console errors and loading forever.

**Comment by mv-tie** [comment]
Hallo zusammen, das Bearbeiten der Kopf-und Fusszeile geht bei mir nun wieder. Es gab ja einige Updates zwischenzeitlich von "Elementor-Header-Footer-Builder!, da wurde das scheinbar behoben. Allerdings ist das Problem mit den kurz erscheinenden Untermenüs auch mit der aktuellesten Version von Elementor immer noch da. Aber immerhin schon mal ein Fehler gelöst-zumindest bei mir. Grüße
