### ISSUE TITLE
A Wordpress failure caused by the plugin header-footer-elementor...

### ISSUE THREAD

**Issue by SwindleMark** [brainstormforce/header-footer-elementor#823]
### To reproduce:
PHP Fatal error:  Uncaught Error: Failed opening required '/home/swindle/leighbienen.com/wp-content/plugins/header-footer-elementor/vendor/autoload.php' (include_path='.:') in /home/swindle/leighbienen.com/wp-content/plugins/header-footer-elementor/header-footer-elementor.php:32
Stack trace:
#0 /home/swindle/leighbienen.com/wp-settings.php(517): include_once()
#1 /usr/local/wp/php/WP_CLI/Runner.php(1365): require('/home/swindle/l...')
#2 /usr/local/wp/php/WP_CLI/Runner.php(1284): WP_CLI\Runner->load_wordpress()
#3 /usr/local/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#4 /usr/local/wp/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#5 /usr/local/wp/php/wp-cli.php(32): WP_CLI\bootstrap()
#6 /usr/local/wp/php/boot-fs.php(17): require_once('/usr/local/wp/p...')
#7 {main}
  thrown in /home/swindle/leighbienen.com/wp-content/plugins/header-footer-elementor/header-footer-elementor.php on line 32

### Expected behavior:
The website posts an error page, and is unsuccessful in loading WP

### Screenshots:
Domain: https://www.leighbienen.com/wp-admin/
There has been a critical error on this website. Please check your site admin email inbox for instructions.

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently using the steps above
- [ X] This bug happens with the Hello Elementor theme WordPress theme active; and Elementor Header & Footer Builder Version 1.6.33

### WordPress version:
Version 6.5.3

### Elementor version:
Version 3.21.6

###Elementor Header & Footer Builder 
Version 1.6.33

**Comment by vijetaR** [comment]
Hi @SwindleMark We have already fixed this issue in version 1.6.30 which is released in the last week. The current plugin version is 1.6.34 So, I would suggest you to update the EHFB plugin to the latest version to resolve the issue.
Thanks for understanding!

**Comment by vijetaR** [comment]
Hello @SwindleMark, We hope you're doing well. We wanted to check in and see if you're still experiencing the issue after the latest update of the Elementor Header Footer Builder plugin version 1.6.35. Please let us know if the problem persists so we can further assist you.

**Comment by vijetaR** [comment]
Hello @SwindleMark,

We hope the latest update of the Elementor Header Footer Builder plugin (v1.6.36) has resolved your issue. If the problem persists, please let us know so we can assist you further. Since we haven't received any recent activity on this issue, we are closing this ticket for now. If you still need assistance or have any further questions, please feel free to reopen this ticket or create a new one.

Thank you.

**Comment by SwindleMark** [comment]
Thank you. Problem solved!





Mark Swindle
i-design | UX Consultant
LinkedIn <https://www.linkedin.com/in/swindle/>  |  Portfolio <http://markswindle.net/> 


2435 N Washtenaw Ave, FL 2
Chicago IL 60647 USA
(312) 212-3346

Carrer Roger de Flor, 204 ATICO
08013 Barcelona SPAIN
+34 659 29 89 61

**Comment by sushant049** [comment]
I am still facing the issue in v1.6.38
