### ISSUE TITLE
Unable to stick footer to the bottom in woocommerce pages with less content

### ISSUE THREAD

**Issue by esterlinpol** [brainstormforce/header-footer-elementor#850]
### Describe the bug:

I am currently using the Elementor Hello theme with Woocommerce. 
In the pages with less content like the My account, cart and other pages, I am unable to make the footer to stick to the bottom of the screen and the footer floats at the end of the content instead of the bottom of the screen.

I tried to fix it using some CSS online but could not fix it.

### To reproduce:

Create a regular footer and go to one of the woocommerce pages.

### Expected behavior:

The footer should show at the bottom of the screen instead of the middle of the screen.

### Screenshots:

![footer-sc](https://github.com/brainstormforce/header-footer-elementor/assets/56879376/4e19246e-cf7d-4fc6-a4b4-3f2c0c4ce3fa)

### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

Latest
### Elementor version:

Latest

**Comment by vijetaR** [comment]
Hi @esterlinpol,
You can fix the footer issue by adding this CSS
How to Add:  
- Go to Appearance > Customize > Additional CSS. Paste the code and publish.
```
.home,
.page {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
}
.admin-bar .home,
.admin-bar .page {
    min-height: calc(100vh - 32px);
}
.home .site-main,
.page .site-main {
    flex-grow: 1;
}
```
This will make sure the footer sticks to the bottom of the screen, even on pages with less content.
I’ve tested it, and it will work. Here’s the screencast: [Screencast](https://bsf.d.pr/v/vYhIQC).
