### ISSUE TITLE
Elementor Header and Footer Version 1.6.38 not loading edit page 

### ISSUE THREAD

**Issue by HankProd** [brainstormforce/header-footer-elementor#864]
### Describe the bug:
I just updated to Version 1.6.38.  When I click on Edit footer or Edit header, it goes to the loading page but never loads. 

### To reproduce:
see above

### Expected behavior:
I expect the Header or Footer edit page to load.

### Screenshots:
https://github.com/user-attachments/assets/888de604-0782-4126-9240-e98f9d16ed01

### Isolating the problem:
Mark completed items with an [x]. -->

- [ X] I can reproduce this bug consistently using the steps above

### WordPress version:
 6.6.1 

### Elementor version:
Version 3.23.4

**Comment by akshayurankar48** [comment]
Hi @HankProd , If you encounter issues with the Elementor – Header Footer & Block Template plugins, such as loading problems or editing difficulties, try the following steps:
1. Deactivate and reactivate the HFE plugin.
2. Switch to a default WordPress theme and then switch back to your current theme.
3. Try flushing WordPress permalinks.
4. Remove HFE plugin and reinstall it.

**Comment by sushmak02** [comment]
Hey @HankProd ,

As we haven't received any activity on this issue recently, we are closing this ticket for now. If you still need assistance or have any further questions, please feel free to reopen this ticket or create a new one.

Thank you for your understanding.
