### ISSUE TITLE
Incompatibility issue with Elementor new version

### ISSUE THREAD

**Issue by lamineneo** [brainstormforce/header-footer-elementor#921]
### Describe the bug:
I updated Elementor and Elementor PRO to their newest versions (V3.25.0) and since then, the website is not working and showing the following screen : 

When I disable Elementor Header & Footer plugin, the website works again. So I think there is an incompatibility between those two plugins.

### Screenshots:
<img width="1183" alt="Capture d’écran 2024-10-28 à 2 14 45 PM" src="https://github.com/user-attachments/assets/ab4b59e9-7e91-4d50-8d9c-388e91ce0b18">

### Debug Result

Uncaught Error: Call to undefined method ElementorPro\Plugin::enqueue_styles() in /home/mswppzi/www/wp-content/plugins/header-footer-elementor/inc/class-header-footer-elementor.php:401
Stack trace:
#0 /home/mswppzi/www/wp-includes/class-wp-hook.php(324): Header_Footer_Elementor->enqueue_scripts('')
#1 /home/mswppzi/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#2 /home/mswppzi/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /home/mswppzi/www/wp-includes/script-loader.php(2263): do_action('wp_enqueue_scri...')
#4 /home/mswppzi/www/wp-includes/class-wp-hook.php(324): wp_enqueue_scripts('')
#5 /home/mswppzi/www/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /home/mswppzi/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /home/mswppzi/www/wp-includes/general-template.php(3065): do_action('wp_head')
#8 /home/mswppzi/www/wp-content/themes/generatepress/header.php(16): wp_head()
#9 /home/mswppzi/www/wp-includes/template.php(810): require_once('/home/mswppzi/w...')
#10 /home/mswppzi/www/wp-includes/template.php(745): load_template('/home/mswppzi/w...', true, Array)
#11 /home/mswppzi/www/wp-includes/general-template.php(48): locate_template(Array, true, true, Array)
#12 /home/mswppzi/www/wp-content/themes/generatepress/page.php(17): get_header()
#13 /home/mswppzi/www/wp-includes/template-loader.php(106): include('/home/mswppzi/w...')
#14 /home/mswppzi/www/wp-blog-header.php(19): require_once('/home/mswppzi/w...')
#15 /home/mswppzi/www/index.php(17): require('/home/mswppzi/w...')
#16 {main}
  thrown

### WordPress version:
Wordpress V6.6.2

### Elementor version:
Elementor V3.25.0
Elementor PRO V3.25.0

**Comment by JHunnicutt** [comment]
I can confirm the same.

WordPress version:
v6.6.2

Elementor version: 
Elementor v3.25.0
Elementor Pro v3.25.0

Elementor Header & Footer Builder:
v1.6.44

**Comment by vijetaR** [comment]
Hello,

We apologize for the inconvenience that has been caused by the recent issues. We are pleased to inform you that we have released an update to fix the issues.

Please update the plugin to the latest version 1.6.45 to resolve the issues.

Thank you for your understanding and patience. If you have any further questions or encounter any issues, please let us know.
