### ISSUE TITLE
site not working suddenly 

### ISSUE THREAD

**Issue by zammilzammil** [brainstormforce/header-footer-elementor#928]
### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently using the steps above

### Elementor version:
![Screenshot_11](https://github.com/user-attachments/assets/46707c4d-4daf-4cfc-a216-ba259dd2f782)

**Comment by vijetaR** [comment]
Hi @zammilzammil 
Thank you for reaching out. To better assist you, could you please provide more details about the issue you’re experiencing on your end? It would be helpful to know which versions of Elementor, Elementor Pro, and the Header Footer for Elementor (HFE) plugin you are using.

Additionally, please ensure that you have updated to the latest versions of these plugins. If possible, send a screencast or screenshot that illustrates the issue in detail. This information will enable us to understand the problem more clearly and assist you effectively.

If the issue still persists, please open a [support ticket](https://brainstormforce.com/open-a-ticket/) and share access to your demo site so we can investigate further. Thank you for your understanding and assistance, we look forward to resolving this for you!

**Comment by zammilzammil** [comment]
site: https://vatwizarduae.com/webdemo/
this is our site and everything was perfect while i tried to update header section suddenly my site was occured this issue

**Comment by zammilzammil** [comment]
![Screenshot_12](https://github.com/user-attachments/assets/876854fe-ceaf-4792-90ed-791580582311)
both theme also working while working on website but suddenly occured this issue while editing header
